version: '3.9'

services:


  nginx:
    image: nginx:1.24
    # build: ./build/nginx
    depends_on:
      - wordpress
    container_name: nginx
    hostname: nginx
    ports:
      - 443:443
    networks:
      net:
        ipv4_address: 13.37.24.2
    volumes:
      - ./build/compose/nginx/confs/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build/compose/nginx/confs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/compose/nginx/confs/server.key:/etc/nginx/conf.d/server.key:ro
      - ./build/compose/nginx/confs/server.crt:/etc/nginx/conf.d/server.crt:ro
      - source:/var/www/html:ro
    env_file: ./build/compose/nginx/.env
    restart: always


  wordpress:
    image: wordpress:php8.2-fpm
    # build: ./build/wordpress
    depends_on:
      - mysql
    container_name: wordpress
    hostname: wordpress
    expose:
      - "9000"
    networks:
      net:
        ipv4_address: 13.37.24.3
    volumes:
      - source:/var/www/html
    env_file: ./build/compose/wordpress/.env
    restart: always


  phpmyadmin:
    image: phpmyadmin:5.2.1
    # build: ./build/phpmyadmin
    depends_on:
        - mysql
    container_name: phpmyadmin
    hostname: phpmyadmin
    expose:
      - "80"
    networks:
      net:
        ipv4_address: 13.37.24.4
    env_file: ./build/compose/phpmyadmin/.env


  mysql:
    image: mysql:8.0
    # build: ./build/mysql
    container_name: mysql
    hostname: mysql
    expose:
      - "3306"
    networks:
      net:
        ipv4_address: 13.37.24.5
    volumes:
      - database:/var/lib/mysql
    env_file: ./build/compose/mysql/.env
    restart: always


volumes:
  database:
  source:

networks:
  net:
    ipam:
      config:
        - subnet: 13.37.24.0/24
