- name: Create phpmyadmin folder
  file:
    path: "{{ PROJECT_DIR }}/build/phpmyadmin"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'
- name: Copy environment files
  template:
    src: "../templates/phpmyadmin.env.j2"
    dest: "{{ PROJECT_DIR }}/build/phpmyadmin/.env"
    owner: vagrant
    group: vagrant
    mode: '0600'