- name: Update apt cache  # Updates the local package metadata
  apt:
    update_cache: yes     # Triggers the apt cache refresh
    cache_valid_time: 3600  # Skips refreshing if last update was less than an hour ago

- name: Install required packages  # Installs common tools for automation and development
  apt:
    name:
      - docker.io          # Installs Docker engine
      - docker-compose     # Installs Docker Compose v1 (deprecated, but still available via apt)
      - python3-pip        # Installs Python package manager
      - git                # Installs Git for version control
      - vim                # Installs Vim text editor
    state: present         # Ensures each package is installed


- name: Upgrade pip to the latest version
  command: python3 -m pip install --upgrade pip
    
# - name: add docker group
#   command: sudo groupadd docker

- name: add user to 'docker' group
  command: sudo usermod -aG docker $USER
  
# - name: activate the changes to groups
#   command: newgrp docker

- name: Create project directory
  file:
    path: "{{ PROJECT_DIR }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'
  
- name: Copy Docker Compose file
  template:
    src: ../templates/docker-compose.yml.j2
    dest: "{{ PROJECT_DIR }}/docker-compose.yml"
    owner: vagrant
    group: vagrant
    mode: '0644'